import type { Metadata } from "next";
import "./globals.css";
import Head from "next/head";
import QueryProvider from "./providers/QueryProvider";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css"
        />
      </Head>
      <body className="pretendard">
        <QueryProvider>
          <Header />
          <div className="wrapper">{children}</div>
        </QueryProvider>
      </body>
    </html>
  );
}
